#!/bin/bash
# Quick start guide for test_mcp servers

echo "==================================="
echo "ChatLlama Test MCP Servers"
echo "==================================="
echo ""
echo "This folder contains two example MCP servers:"
echo ""
echo "1. Fashion Advisor (Stdio) - fashion_stdio.py"
echo "   - Simple, stateless fashion recommendations"
echo "   - Runs via stdio transport"
echo "   - Best for: Lightweight integrations"
echo ""
echo "2. Fashion Curator (Server) - fashion_server/server.py"
echo "   - Stateful user profiles and personalization"
echo "   - Runs as an HTTP server"
echo "   - Best for: Complex interactions with state"
echo ""
echo "==================================="
echo "Testing the Stdio MCP:"
echo "==================================="
echo ""
echo "To test the stdio MCP:"
echo "  conda activate chatllama"
echo "  python fashion_stdio.py"
echo ""
echo "This will start the MCP server listening on stdin/stdout"
echo ""
echo "==================================="
echo "Starting the Server MCP:"
echo "==================================="
echo ""
echo "To run the stateful server MCP:"
echo "  conda activate chatllama"
echo "  python fashion_server/server.py"
echo ""
echo "This will start the server on the default MCP port."
echo ""
echo "==================================="
echo "Integration with ChatLlama:"
echo "==================================="
echo ""
echo "1. For stdio MCP (fashion_stdio.py):"
echo "   - Add to chat.py MCP configuration with stdio transport"
echo "   - It will be called for simple tool invocations"
echo ""
echo "2. For server MCP (fashion_server):"
echo "   - Start the server in a separate terminal"
echo "   - Configure ChatLlama to connect to its HTTP endpoint"
echo "   - Maintains user state across multiple requests"
echo ""
